### ISSUE TITLE
Will you add support of other less-common extensions which aren't supported by Sublime?

### ISSUE THREAD

**Issue by marcofugaro** [oivva/zz-file-icons#2]
Such as  .htaccess, .hx, .pug, .vue, .ts, .swift, Dockerfile.

Those are pretty common nowadays, but not actually picked up from Sublime even if the theme is already configured.

Here is the theme I've been working on implementing sidebar icons, works good with your plugin: https://github.com/marcofugaro/spacegray/tree/betterfileicons

**Comment by oivva** [comment]
@marcofugaro Wait 2.0.0 I'm working on that :wink:

**Comment by oivva** [comment]
> .pug, .vue, .ts, .swift, Dockerfile
Currently they are supported only from theme side. See [Boxy Theme](https://github.com/oivva/st-boxy).

**Comment by skalfyfan** [comment]
Definitely looking forward to support for .jsx, .vue, Dockerfile, .ts, and .go! +1

**Comment by oivva** [comment]
Ok, it's ready to release. We're waiting only for https://github.com/wbond/package_control_channel/pull/5852. I'll publish 2.0.0 right after closing that.
