### ISSUE TITLE
eslint icon vs. yaml icon

### ISSUE THREAD

**Issue by equinusocio** [oivva/zz-file-icons#5]
#### Expected Behavior
Thoughts about the `eslint.yml` icon. What's more important to users? recognize that is an eslint configuration or a `yaml` file? My personal suggestion is to use the default `yaml` icon even for eslint files. In my case i know that i'm searching for the eslint configuration (the file name tell me that) but first will start to search for a yaml icon (file) that contain `eslint` inside the name.

I think this is a different case from Gulpfile, Gruntfile, ecc...

#### Current Behavior
eslint yaml files show the eslint icon instead for the default yaml icon.

#### Possible Solution
Show the default yaml icon.

Just a thought..

**Comment by oivva** [comment]
I agree with you. I did it because `Atom File Icons` does it, however I like the behavior you described more. I think I'll fix it, because we should minimize usage of the syntax aliases.
